// Generated by CoffeeScript 1.9.3
(function() {
  var func_info;

  func_info = __F('info');

  module.exports = function(req, res, next) {
    return func_info.getAll(1, 10, {
      type: [1, 2, 3, 4, 5, 7, 9]
    }, "id desc", function(error, infos) {
      res.locals.actives = infos;
      return next();
    });
  };

}).call(this);
