// Generated by CoffeeScript 1.9.3
(function() {
  var func_tag;

  func_tag = __F('qa/channel');

  module.exports = function(req, res, next) {
    if (req.query.page) {
      next();
      return;
    }
    return func_tag.getAll(1, 100, null, "id asc", function(error, tags) {
      res.locals.tags = tags;
      return next();
    });
  };

}).call(this);
