// Generated by CoffeeScript 1.9.3
(function() {
  var func_topic;

  func_topic = __F('topic');

  module.exports = function(req, res, next) {
    if (req.query.page) {
      next();
      return;
    }
    return func_topic.getAll(1, 13, null, "sort desc,id desc", function(error, topics) {
      res.locals.topics = topics;
      return next();
    });
  };

}).call(this);
