// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    if (req.query.page) {
      next();
      return;
    }
    return func_article.getAll(1, 13, {
      is_publish: 1
    }, function(error, articles) {
      if (error) {
        console.log(error);
      }
      res.locals.articles = articles;
      return next();
    });
  };

}).call(this);
