// Generated by CoffeeScript 1.9.3
(function() {
  var func_column;

  func_column = __F('column');

  module.exports = function(req, res, next) {
    if (req.query.page) {
      next();
      return;
    }
    return func_column.getAll(1, 10, null, "last_article_time desc", function(error, columns) {
      res.locals.columns = columns;
      return next();
    });
  };

}).call(this);
