// Generated by CoffeeScript 1.9.3
(function() {
  var func_question;

  func_question = __F('question');

  module.exports = function(req, res, next) {
    if (req.query.page) {
      next();
      return;
    }
    return func_question.getAll(1, 12, null, "sort desc,id desc", function(error, questions) {
      res.locals.questions = questions;
      return next();
    });
  };

}).call(this);
