// Generated by CoffeeScript 1.9.3
(function() {
  var func_count;

  func_count = __F('user/count');

  module.exports = function(req, res, next) {
    return func_count.getTopUser("topic_comment_count", 12, function(error, users) {
      if (users) {
        res.locals.topic_top_users = users;
      }
      return next();
    });
  };

}).call(this);
