// Generated by CoffeeScript 1.9.3
(function() {
  var Book, User, func_book;

  Book = __M('books');

  Book.sync();

  User = __M('users');

  func_book = {
    sellToUser: function(bookId, user, callback) {
      return Book.find({
        where: {
          id: bookId
        }
      }).success(function(book) {
        if (!book) {
          return callback(new Error('不存在的书籍'));
        } else {
          return book.updateAttributes({
            user_id: user.id,
            user_nick: user.nick,
            is_selled: 1
          }).success(function() {
            return callback(null, book);
          }).error(function(e) {
            return callback(e);
          });
        }
      }).error(function(e) {
        return callback(e);
      });
    },
    getByUserId: function(userId, callback) {
      return Book.findAll({
        where: {
          user_id: userId
        }
      }).success(function(books) {
        return callback(null, books);
      }).error(function(e) {
        return callback(e);
      });
    },
    getByPubUserId: function(userId, callback) {
      return Book.findAll({
        where: {
          pub_user_id: userId
        }
      }).success(function(books) {
        return callback(null, books);
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_book, Book, ['add', 'getAll', 'delete', 'update', 'count', 'getById']);

  module.exports = func_book;

}).call(this);
