// Generated by CoffeeScript 1.9.3
(function() {
  var LocalMail, Mail, func_mail;

  Mail = __M('cloudmails');

  LocalMail = __M('localmails');

  Mail.sync();

  LocalMail.sync();

  func_mail = {
    addLocalEmail: function(source, target, user_id, callback) {
      return LocalMail.create({
        source_mail: source,
        target_mail: target,
        user_id: user_id
      }).success(function(m) {
        return callback(null, m);
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_mail, Mail, ['getAll', 'update', 'count', 'delete', 'getById', 'add']);

  module.exports = func_mail;

}).call(this);
