// Generated by CoffeeScript 1.9.3
(function() {
  var Comment, func_comment;

  Comment = __M('comments');

  Comment.sync();

  func_comment = {
    getAllByTargetId: function(target_id, page, count, condition, order, callback) {
      var query;
      if (arguments.length === 5) {
        callback = order;
        order = null;
      }
      query = {
        offset: (page - 1) * count,
        limit: count,
        order: order || "id desc",
        where: {
          target_id: target_id
        },
        raw: true
      };
      if (condition) {
        query.where = condition;
      }
      return Comment.findAll(query).success(function(ms) {
        return callback(null, ms);
      }).error(function(e) {
        return callback(e);
      });
    },
    getCommentByFilter: function(filter, page, count, callback) {
      var query;
      query = {
        offset: (page - 1) * count,
        limit: count,
        order: "id desc",
        where: ["target_id like ?", "%" + filter + "%"],
        raw: true
      };
      return Comment.findAll(query).success(function(ms) {
        return callback(null, ms);
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_comment, Comment, ['getAll', 'update', 'delete', 'getById', 'add']);

  module.exports = func_comment;

}).call(this);
