// Generated by CoffeeScript 1.9.3
(function() {
  var mail, mustache;

  mail = require('./../lib/mail.js');
  var tplmail = require("./../lib/tpl_mail.js")
  mustache = require('mu2');
  var async = require("async")
  module.exports = {
    sendQAInvite: function(qa, emails) {
      var buffer;
      buffer = "";
      return mustache.compileAndRender('./views/mail/qa-invite.html', qa).on('data', function(c) {
        return buffer += c.toString();
      }).on('end', function() {
        return mail({
          subject: qa.user_nick + " 在前端乱炖问答频道 邀请您回答问题",
          to: emails,
          html: buffer
        });
      });
    },
    sendCardComment: function(source_user_nick, card) {
      var buffer;
      if (!card.email) {
        return;
      }
      buffer = "";
      card.source_user_nick = source_user_nick;
      return mustache.compileAndRender('./views/mail/card-comment.html', card).on('data', function(c) {
        return buffer += c.toString();
      }).on('end', function() {
        return mail({
          subject: source_user_nick + " 在 前端乱炖花名册 评论了你的名片",
          to: card.email,
          html: buffer
        });
      });
    },
    sendArticleComment: function(source_user, article_user, article) {
      

       tplmail({
          subject:source_user.nick + " 在 前端乱炖 评论了你的原创文章",
          substitution_vars:JSON.stringify({
            to:[article_user.email],
            sub:{
              "%source_user_nick%":[source_user.nick],
              "%title%":[article.title],
              "%id%":[article.id]
            }
          }),
          template_invoke_name:"article_comment",
        },function(){
        });
    },
    sendMessage: function(email, data) {
      
      tplmail({
          subject:data.title,
          substitution_vars:JSON.stringify({
            to:[email],
            sub:{
              "%content%":[data.content],
              "%url%":[data.url],
              "%title%":[data.title]
            }
          }),
          template_invoke_name:"common",
        });
    },
    sendAnswer: function(answer, question, card) {
      answer.title = question.title;
      

      tplmail({
          subject:answer.user_nick + " 在 前端乱炖 回答了你的提问",
          substitution_vars:JSON.stringify({
            to:[card.email],
            sub:{
              "%content%":['<p style="font-size:14px;">你好，'+answer.user_nick+' 回答了您的问题 《<a href="http://www.html-js.com/qa/'+answer.question_id+'">'+answer.title+'</a>》</p><div style="padding:10px 20px;"><p style="font-size:13px;">'+answer.html+'</p></div>'],
              "%url%":['http://www.html-js.com/qa/'+answer.question_id],
              "%title%":[answer.user_nick+'回答了你的提问']
            }
          }),
          template_invoke_name:"common",
        },function(){
        });
    },
    sendArticleRss: function(article, emails) {
      var buffer;
      buffer = "";
      console.log(emails);
      var emails = emails.split(";");
      if(emails.indexOf("xinyu198736@gmail.com")==-1){
        emails.push('xinyu198736@gmail.com')
      }
      async.eachLimit(emails,2,function(email,cb){
        tplmail({
          subject: "前端乱炖专栏新文章：" + article.title,
          substitution_vars:JSON.stringify({
            to:[email],
            sub:{
              "%user_nick%":[article.user_nick],
              "%id%":[article.id],
              "%title%":[article.title],
              "%html%":[article.html.substr(0,1000)]
            }
          }),
          template_invoke_name:"new_article",
        },function(){
          cb();
        });
        
      })
      
    },
    sendColumnNotify: function(column, card, rsses) {
      
      tplmail({
          subject:"您在前端乱炖的专栏被订阅了，赶紧来更新文章吧！",
          substitution_vars:JSON.stringify({
            to:[card.email],
            sub:{
              "%content%":['<div style="padding:10px 20px;"><p style="font-size:16px;">至今为止，已经有'+column.rss_count+'人订阅了您的专栏<a href="http://www.html-js.com/article/column/'+column.id+'">「'+column.name+'」 </a></p><p style="font-size:16px;">大家非常期待专栏文章的更新</p></div>'],
              "%url%":[data.url],
              "%title%":['您在前端乱炖的专栏被订阅了，赶紧来更新文章吧！']
            }
          }),
          template_invoke_name:"common",
        },function(){
        });
    }
  };

}).call(this);
