// Generated by CoffeeScript 1.9.3
(function() {
  var Info, func_info;

  Info = __M('infos');

  Info.sync();

  func_info = {
    getByUserId: function(user_id, callback) {
      return Info.findAll({
        where: {
          is_read: 0,
          target_user_id: user_id
        },
        raw: true
      }).success(function(infos) {
        return callback(null, infos);
      }).error(function(e) {
        return callback(e);
      });
    },
    add: function(data, callback) {
      if (data.target_user_id === data.source_user_id) {
        return;
      }
      return Info.create(data).success(function(info) {
        return callback && callback(null, info);
      }).error(function(e) {
        return callback && callback(e);
      });
    },
    read: function(user_id, callback) {
      return sequelize.query('update infos set is_read = 1 where target_user_id = ?', null, {
        raw: true
      }, [user_id]);
    }
  };

  __FC(func_info, Info, ['getAll', 'getById', 'delete', 'update', 'count']);

  module.exports = func_info;

}).call(this);
