// Generated by CoffeeScript 1.9.3
(function() {
  var Keyword, Segment, fenci, filter_keywords, segment;

  Segment = require('segment').Segment;

  segment = new Segment();

  segment.useDefault();

  filter_keywords = require('./../lib/filter_keyword.js');

  Keyword = __M('keywords');

  fenci = function(string) {
    var items, result;
    items = segment.doSegment(string);
    result = [];
    return items.forEach(function(item) {
      if (filter_keywords.indexOf(item.w === -1)) {
        return result.push(item.w);
      }
    });
  };

  module.exports = {
    fenxiArticle: function(article, callback) {
      return Keyword.find({
        where: {
          uuid: article.uuid
        }
      }).success(function(k) {
        if (k) {
          return callback(new Error('已经添加过此文章的索引'));
        }
      });
    }
  };

}).call(this);
