// Generated by CoffeeScript 1.9.3
(function() {
  var Music, func;

  Music = new __BaseModel('music_play');

  Music.sync();

  func = new __BaseFunction(Music);
func.get = function(query, callback){
  	Music.find({where:query}).success(function(m) {
      return callback(null, m);
    }).error(function(e) {
      return callback(e);
    });
  }
  module.exports = func;

}).call(this);
