// Generated by CoffeeScript 1.9.3
(function() {
  var Music, func;

  Music = new __BaseModel('musics');

  Music.sync();

  func = new __BaseFunction(Music);

  func.getNext = function(id, callback) {
    return Music.find({
      where: ['id<?', id],
      order: "id desc"
    }).success(function(m) {
      return callback(null, m);
    }).error(function(e) {
      return callback(e);
    });
  };

  module.exports = func;

}).call(this);
