// Generated by CoffeeScript 1.9.3
(function() {
  var Trade, func_payment;

  Trade = __M('payments');

  Trade.sync();

  func_payment = {
    getByTradeNum: function(trade_num, callback) {
      return Trade.find({
        where: {
          trade_num: trade_num
        }
      }).success(function(payment) {
        if (!payment) {
          return callback(new Error('不存在的订单'));
        } else if (payment.status !== 1) {
          return callback(new Error('订单已经被支付'));
        } else {
          return callback(null, payment);
        }
      }).error(function(e) {
        return callback(e);
      });
    },
    getByTradeNumNoCheck: function(trade_num, callback) {
      return Trade.find({
        where: {
          trade_num: trade_num
        }
      }).success(function(payment) {
        if (!payment) {
          return callback(new Error('不存在的订单'));
        } else {
          return callback(null, payment);
        }
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_payment, Trade, ['get', 'add', 'update', 'delte']);

  module.exports = func_payment;

}).call(this);
