// Generated by CoffeeScript 1.9.3
(function() {
  var Email, func_email;

  Email = __M('emails');

  Email.sync();

  func_email = new __BaseFunction(Email);

  func_email.add = function(data, callback) {
    return Email.find({
      where: {
        email: data.email
      }
    }).success(function(e) {
      if (e) {
        return callback && callback(new Error('此邮箱已经订阅过'));
      } else {
        return Email.create(data).success(function(m) {
          return callback && callback(null, m);
        }).error(function(error) {
          return callback && callback(error);
        });
      }
    }).error(function(e) {
      return callback && callback(e);
    });
  };

  module.exports = func_email;

}).call(this);
