// Generated by CoffeeScript 1.9.3
(function() {
  var Tip, func;

  Tip = new __BaseModel('tips');

  Tip.sync();

  func = new __BaseFunction(Tip);

  func.getAllByTargetId = function(target_id, callback) {
    return Tip.findAll({
      where: {
        target_id: target_id,
        parent_id: null
      }
    }).success(function(tips) {
      return callback(null, tips);
    }).error(function(e) {
      return callback(e);
    });
  };

  module.exports = func;

}).call(this);
