// Generated by CoffeeScript 1.9.3
(function() {
  var Tool, func_tool;

  Tool = __M('tools');

  Tool.sync();

  func_tool = {
    getByName: function(name, callback) {
      return Tool.find({
        where: {
          name: name
        }
      }).success(function(tool) {
        if (!tool) {
          return callback(new Error('不存在的工具'));
        } else {
          return callback(null, tool);
        }
      }).error(function(e) {
        return callback(e);
      });
    },
    addCountByName: function(name, callback) {
      return Tool.find({
        where: {
          name: name
        }
      }).success(function(tool) {
        if (!tool) {
          return callback(new Error('不存在的工具'));
        } else {
          return tool.updateAttributes({
            visit_count: tool.visit_count * 1 + 1
          }).success(function() {
            return callback(null, tool);
          });
        }
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_tool, Tool, ['add', 'update', 'getAll', 'addCount']);

  module.exports = func_tool;

}).call(this);
