// Generated by CoffeeScript 1.9.3
(function() {
  var Topic, TopicComment, func_comment;

  TopicComment = __M('topic_comments');

  TopicComment.sync();

  Topic = __M('topics');

  func_comment = {
    add: function(data, callback) {
      return Topic.find({
        where: {
          id: data.topic_id
        }
      }).success(function(topic) {
        if (!topic) {
          return callback(new Error('不存在的话题'));
        } else {
          data.uuid = (require('node-uuid')).v4();
          return TopicComment.create(data).success(function(comment) {
            return callback(null, comment, topic);
          }).error(function(e) {
            return callback(e);
          });
        }
      }).error(function(e) {
        return callback(e);
      });
    },
    getLast: function(topic_id, user_id, callback) {
      return TopicComment.find({
        where: {
          topic_id: topic_id,
          user_id: user_id
        },
        order: "id desc"
      }).success(function(comment) {
        if (comment) {
          return callback(null, comment);
        } else {
          return callback(new Error('no comment'));
        }
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_comment, TopicComment, ['update', 'delete', 'count', 'getAll', 'addCount', 'getById']);

  module.exports = func_comment;

}).call(this);
