// Generated by CoffeeScript 1.9.3
(function() {
  var Tag, Topic, func_tag;

  Tag = __M('topic/tags');

  Tag.sync();

  Topic = __M('topics');

  Topic.belongsTo(Tag, {
    foreignKey: "tag_id"
  });

  Tag.hasMany(Topic, {
    foreignKey: "tag_id"
  });

  func_tag = {
    getAllWithTopic: function(page, count, condition, order, include, callback) {
      var query;
      if (arguments.length === 4) {
        callback = order;
        order = null;
        include = null;
      } else if (arguments.length === 5) {
        callback = include;
        include = null;
      }
      query = {
        offset: (page - 1) * count,
        limit: count,
        order: order || "id desc",
        raw: true,
        include: [Topic]
      };
      if (condition) {
        query.where = condition;
      }
      if (include) {
        query.include = include;
      }
      return Tag.findAll(query).success(function(ms) {
        return callback(null, ms);
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_tag, Tag, ['getById', 'add', 'delete', 'update', 'getAll', 'count', 'addCount']);

  module.exports = func_tag;

}).call(this);
