// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    var count, page;
    page = req.query.page || 1;
    count = req.query.count || 30;
    return (__F('act')).count(null, function(error, _count) {
      if (error) {
        return next(error);
      } else {
        res.locals.total = _count;
        res.locals.totalPage = Math.ceil(_count / count);
        res.locals.page = req.query.page || 1;
        return (__F('act')).getAll(page, count, null, function(error, acts) {
          if (error) {
            return next(error);
          } else {
            res.locals.acts = acts;
            return next();
          }
        });
      }
    });
  };

}).call(this);
