// Generated by CoffeeScript 1.9.3
(function() {
  var ArrayUtil;

  ArrayUtil = require('./../../lib/array-util.coffee');

  module.exports = function(req, res, next) {
    return (__F('book')).getAll(1, 50, {}, function(error, books) {
      if (error) {
        return next(error);
      } else {
        res.locals.r_books = ArrayUtil.randomItem(books, 10);
        return next();
      }
    });
  };

}).call(this);
