// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "int",
    name: "",
    sex: "",
    jiguan: "",
    location: "",
    shengri: "",
    phone: "",
    email: "",
    blog: "",
    yixiang: "",
    jingyan: "",
    gongzuojingyan_md: "text",
    gongzuojingyan_html: "text",
    jineng_md: "text",
    jineng_html: "text",
    desc_md: "text",
    desc_html: "text",
    jiaoyu_md: "text",
    jiaoyu_html: "text",
    other_md: "text",
    other_html: "text",
    attachment: "varchar(500)"
  };

}).call(this);
