// Generated by CoffeeScript 1.9.3
(function() {
  module.exports.controllers = {
    "/": {
      get: function(req, res, next) {
        return res.render('app/index');
      }
    },
    "/column": {
      get: function(req, res, next) {
        return res.render('app/column');
      }
    },
    "/blog/:id": {
      get: function(req, res, next) {
        res.locals.id = req.params.id;
        return res.render('app/blog');
      }
    },
    "/article/:id": {
      get: function(req, res, next) {
        res.locals.id = req.params.id;
        return res.render('app/article');
      }
    }
  };

}).call(this);
