// Generated by CoffeeScript 1.9.3
(function() {
  var Sina, config, func_book, request;

  func_book = __F('book');

  request = require('request');

  config = require('./../config.coffee');

  Sina = require("./../lib/sdk/sina.js");

  module.exports.controllers = {
    "/": {
      get: function(req, res, next) {
        return res.render('book/books.jade');
      }
    },
    "/add": {
      get: function(req, res, next) {
        return res.render('book/add.jade');
      },
      post: function(req, res, next) {
        req.body.pub_user_id = res.locals.user.id;
        req.body.pub_user_nick = res.locals.user.nick;
        return func_book.add(req.body, function(error, callback) {
          if (error) {
            return next(error);
          } else {
            return res.redirect('/book');
          }
        });
      }
    },
    "/:id/buy": {
      get: function(req, res, next) {
        return func_book.sellToUser(req.params.id, res.locals.user, function(error, book) {
          var sina;
          if (error) {
            return next(error);
          } else {
            sina = new Sina(config.sdks.sina);
            sina.statuses.update({
              access_token: res.locals.user.weibo_token,
              status: "我在@前端乱炖 免费获得了一本《" + book.title + "》,名额有限，速度来抢！http://www.html-js.com/book"
            });
            return res.redirect('back');
          }
        });
      }
    },
    "/:id/del": {
      get: function(req, res, next) {
        return func_book.getById(req.params.id, function(error, book) {
          if (error) {
            return next(error);
          } else if (book) {
            if (res.locals.user.id === book.pub_user_id) {
              return book.destroy().success(function() {
                return res.redirect('back');
              }).error(function(e) {
                return next(e);
              });
            } else {
              return next(new Error('没有权限'));
            }
          } else {
            return next(new Error('不存在的书籍'));
          }
        });
      }
    },
    "/isbn_to_info": {
      "get": function(req, res, next) {
        var result;
        result = {
          success: 0,
          info: ""
        };
        return request.get({
          url: 'https://api.douban.com/v2/book/isbn/' + req.query.isbn
        }, function(e, r, body) {
          if (e) {
            result.info = e.message;
          } else {
            result.success = 1;
            try {
              result.data = JSON.parse(body);
            } catch (_error) {
              e = _error;
              result.info = e.message;
              result.success = 0;
            }
          }
          return res.send(result);
        });
      }
    }
  };

  module.exports.filters = {
    "/": {
      get: ['freshLogin', 'checkCard', 'book/all-books', 'book/my-book', 'book/my-pub-book']
    },
    "/add": {
      post: ['checkLogin', 'book/check-add']
    },
    "/:id/del": {
      get: ['checkLogin']
    },
    "/:id/buy": {
      get: ['checkLogin', 'checkCard', 'book/check-user']
    }
  };

}).call(this);
