// Generated by CoffeeScript 1.9.3
(function() {
  var fs, func_mail, uuid;

  func_mail = __F('cloudmail');

  fs = require("fs");

  uuid = require('node-uuid');

  module.exports.controllers = {
    "/post_raw/recieve": {
      post: function(req, res, next) {
        func_mail.add(req.body, function(error) {
          return console.log(error);
        });
        console.log(req.files);
        console.log(req.body);
        return res.send("ok");
      }
    },
    "/recieve": {
      post: function(req, res, next) {
        var baseExp, buffer, fileNameExp, fileNameResult, filename, raw_message, result;
        raw_message = req.body.raw_message;
        baseExp = /\n\n([A-Za-z0-9+\/\n]*)\n\n/;
        fileNameExp = /filename=(.*?)\n/;
        result = raw_message.match(baseExp);
        fileNameResult = raw_message.match(fileNameExp);
        filename = "";
        if (result && fileNameResult) {
          buffer = new Buffer(result[1], "base64");
          filename = __C.resume_path + "/" + uuid.v4() + "-" + req.body.from + "-" + req.body.fromname + "-" + req.body.to + "-" + fileNameResult[1];
          fs.writeFileSync(filename, buffer);
        }
        req.body.filepath = filename;
        func_mail.add(req.body, function(error) {
          return console.log(error);
        });
        console.log(req.body);
        console.log(req.file);
        return res.send("ok");
      }
    }
  };

}).call(this);
