// Generated by CoffeeScript 1.9.3
(function() {
  var func_talk;

  func_talk = __F('talk/talk');

  module.exports.controllers = {
    "/": {
      get: function(req, res, next) {
        return res.render('talk/talk.jade');
      }
    }
  };

  module.exports.filters = {
    "/": {
      get: ['freshLogin', 'talk/all-talks']
    }
  };

}).call(this);
