// Generated by CoffeeScript 1.9.3
(function() {
  var Sina;

  Sina = require("./../lib/sdk/sina.js");

  module.exports.controllers = {
    "/": {
      get: function(req, res, next) {
        return res.render('toutiao/index.jade');
      },
      post: function(req, res, next) {
        var result;
        return result = {
          success: 0,
          info: ""
        };
      }
    }
  };

  module.exports.filters = {
    "/": {
      post: ['checkLoginJson']
    }
  };

}).call(this);
