// Generated by CoffeeScript 1.9.3
(function() {
  module.exports.controllers = {
    "/": {
      get: function(req, res, next) {
        return res.render('weekly/index.jade');
      }
    }
  };

}).call(this);
