// Generated by CoffeeScript 1.9.3
(function() {
  var d, func_article, func_column, func_rss_email, func_search, func_topic, wechat;

  wechat = require('wechat');

  func_article = __F('article/article');

  func_column = __F('column');

  func_topic = __F('topic');

  func_search = __F('search');

  func_rss_email = __F('rss_email');

  d = "你好，欢迎使用前端乱炖公众号系统\n回复1查看最新原创文章，\n回复2查看最近更新专栏，\n回复3查看最新讨论，\n回复：\"搜索：关键词\"可以使用本站的搜索系统搜索信息。\n回复：\"订阅：email地址\"可以订阅本站推出的乱炖周刊。\n也欢迎偶尔调戏下小炖(๑╹∀╹๑)萌。";

  module.exports.controllers = {
    "/api": {
      get: wechat("xinyu198736", function(req, res, next) {
        return console.log(req.query);
      }),
      "post": wechat('xinyu198736', function(req, res, next) {
        var info, match, message, username;
        info = req.weixin;
        username = info.FromUserName;
        message = info.Content ? info.Content : "";
        console.log(req.weixin);
        if (message.length > 10) {
          res.send('0k');
        }
        if (info.Event === "subscribe" || message === "?") {
          return res.reply(d);
        } else if (message === "1") {
          return func_article.getAll(1, 10, {
            is_publish: 1,
            is_yuanchuang: 1
          }, "id desc", function(error, articles) {
            var news;
            news = [];
            articles.forEach(function(a) {
              return news.push({
                title: a.title,
                description: a.title,
                picurl: a.main_pic ? a.main_pic : a.user_headpic,
                url: "http://www.html-js.com/article/" + a.id
              });
            });
            return res.reply(news);
          });
        } else if (message === "2") {
          return func_column.getAll(1, 7, {
            is_publish: 1
          }, "last_article_time desc,visit_count desc", function(error, articles) {
            var news;
            news = [];
            articles.forEach(function(a) {
              return news.push({
                title: a.name,
                description: a.name,
                picurl: a.user_headpic,
                url: "http://www.html-js.com/article/column/" + a.id
              });
            });
            return res.reply(news);
          });
        } else if (message === "3") {
          return func_topic.getAll(1, 7, null, "last_comment_time desc,id desc", function(error, articles) {
            var news;
            news = [];
            articles.forEach(function(a) {
              return news.push({
                title: a.title,
                description: a.title,
                picurl: a.user_headpic,
                url: "http://www.html-js.com/topic/" + a.id
              });
            });
            return res.reply(news);
          });
        } else if (message.substr(0, 2) === "搜索") {
          return func_search.query({
            "query": message.substr(3, message.length - 1),
            "limit": 7,
            "offset": 0
          }, function(error, data) {
            var news, results;
            data = JSON.parse(data);
            results = data.data;
            news = [];
            results.forEach(function(result) {
              var title;
              title = "";
              if (result.type === 'article') {
                title += '「专栏」';
              } else if (result.type === 'card') {
                title += '「花名册」';
              } else if (result.type === 'qa') {
                title += '「问题」';
              } else if (result.type === 'topic') {
                title += '「话题」';
              } else if (result.type === 'answer') {
                title += '「回答」';
              } else if (result.type === 'blog') {
                title += '「站外博客」';
              }
              return news.push({
                title: title + result.title.replace(/<[^>]*?>/g, ""),
                description: title + result.title.replace(/<[^>]*?>/g, ""),
                picurl: "http://www.html-js.com/assets/images/logo.png",
                url: "http://www.html-js.com/" + result.type + "/" + result.id
              });
            });
            if (news.length === 0) {
              return res.reply('对不起，没有搜索到任何相关信息，尝试换一下关键字吧少年！');
            } else {
              return res.reply(news);
            }
          });
        } else if (message.substr(0, 2) === "订阅") {
          match = message.match(/(\w)+(\.\w+)*@(\w)+((\.\w+)+)/);
          if (match) {
            return func_rss_email.add({
              email: match[0]
            });
          }
        } else if (message.substr(0, 2) === "抽奖") {
          return res.reply('恭喜您，报名抽奖成功！请在微博关注抽奖结果！');
        }
      })
    }
  };

}).call(this);
