// Generated by CoffeeScript 1.9.3
(function() {
  var func_channel;

  func_channel = __F('qa/channel');

  module.exports = function(req, res, next) {
    if (res.locals.question.channel_id) {
      return func_channel.getById(res.locals.question.channel_id, function(error, channel) {
        res.locals.channel = channel;
        return next();
      });
    } else {
      return next();
    }
  };

}).call(this);
