// Generated by CoffeeScript 1.9.3
(function() {
  var Counts, Users, func_counts;

  Counts = __M('user_counts');

  Counts.sync();

  Users = __M('users');

  func_counts = {
    addCount: function(user_id, field, callback) {
      return Counts.find({
        where: {
          user_id: user_id
        }
      }).success(function(user) {
        var query, updates;
        if (!user) {
          query = {
            user_id: user_id
          };
          query[field] = 1;
          return Users.find({
            where: {
              id: user_id
            }
          }).success(function(uu) {
            if (uu) {
              query.user_nick = uu.nick;
              query.user_headpic = uu.head_pic;
              return Counts.create(query).success(function() {
                return callback(null);
              }).error(function(e) {
                return callback(e);
              });
            }
          });
        } else {
          updates = {};
          updates[field] = user[field] * 1 + 1;
          return user.updateAttributes(updates, [field]).success(function() {
            return callback && callback(null, user);
          }).error(function(error) {
            return callback && callback(error);
          });
        }
      }).error(function(e) {
        return callback && callback(e);
      });
    },
    getTopUser: function(field, count, callback) {
      return Counts.findAll({
        offset: 0,
        limit: count,
        order: field + " desc",
        raw: true
      }).success(function(users) {
        return callback(null, users);
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_counts, Counts, ['getAll', 'add', 'getByField']);

  module.exports = func_counts;

}).call(this);
