// Generated by CoffeeScript 1.9.3
(function() {
  var FavHis, func_fav_his;

  FavHis = __M('user/fav_history');

  FavHis.sync();

  func_fav_his = {};

  __FC(func_fav_his, FavHis, ['getAll', 'add']);

  module.exports = func_fav_his;

}).call(this);
