// Generated by CoffeeScript 1.9.3
(function() {
  var VisitLog, func_vl;

  VisitLog = __M('visit_log');

  func_vl = {};

  __FC(func_vl, VisitLog, ['add']);

  module.exports = func_vl;

}).call(this);
