// Generated by CoffeeScript 1.9.3
(function() {
  var func_coin;

  func_coin = __F('coin');

  module.exports = function(req, res, next) {
    var count, page;
    page = req.query.page || 1;
    count = req.query.count || 30;
    return func_coin.count({
      user_id: res.locals.user.id
    }, function(error, _count) {
      if (error) {
        return next(error);
      } else {
        res.locals.total = _count;
        res.locals.totalPage = Math.ceil(_count / count);
        res.locals.page = req.query.page || 1;
        return func_coin.getAll(page, count, {
          user_id: res.locals.user.id
        }, "createdAt desc", function(error, coinhis) {
          if (error) {
            return next(error);
          } else {
            res.locals.coinhis = coinhis;
            return next();
          }
        });
      }
    });
  };

}).call(this);
