// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    var count, page;
    page = req.query.page || 1;
    count = req.query.count || 30;
    return func_article.count({
      user_id: res.locals.user.id,
      is_yuanchuang: 1
    }, function(error, _count) {
      if (error) {
        return next(error);
      } else {
        res.locals.total = _count;
        res.locals.totalPage = Math.ceil(_count / count);
        res.locals.page = req.query.page || 1;
        return func_article.getAll(page, count, {
          user_id: res.locals.user.id,
          is_yuanchuang: 1
        }, function(error, articles) {
          if (error) {
            return next(error);
          } else {
            res.locals.articles = articles;
            return next();
          }
        });
      }
    });
  };

}).call(this);
