// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    return (__F('user')).getAll(1, 15, null, "coin desc", function(error, users) {
      res.locals.top_users = users;
      return next();
    });
  };

}).call(this);
