// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    if (res.locals.user) {
      return (__F('job/resume')).getByField("user_id", res.locals.user.id, function(error, resume) {
        if (error) {
          return next(error);
        } else {
          res.locals.resume = resume;
          return next();
        }
      });
    } else {
      return next();
    }
  };

}).call(this);
