// Generated by CoffeeScript 1.9.3
(function() {
  var func_job;

  func_job = __F('job/job');

  module.exports = function(req, res, next) {
    return func_job.getById(req.params.id, function(error, job) {
      if (error) {
        return next(error);
      } else {
        res.locals.job = job;
        return next();
      }
    });
  };

}).call(this);
