// Generated by CoffeeScript 1.9.3
(function() {
  var func_job;

  func_job = __F('job/job');

  module.exports = function(req, res, next) {
    return func_job.getAll(1, 10, {
      "user_id": res.locals.job.user_id
    }, 'sort desc,id desc', function(error, jobs) {
      res.locals.user_jobs = jobs;
      return next();
    });
  };

}).call(this);
