// Generated by CoffeeScript 1.9.3
(function() {
  var func_job;

  func_job = __F('job/job');

  module.exports = function(req, res, next) {
    var condition, count, page;
    condition = {
      is_jian: 1
    };
    page = req.query.page || 1;
    count = req.query.count || 10;
    return func_job.getAll(page, count, condition, 'id desc', function(error, jobs) {
      if (error) {
        return next(error);
      } else {
        res.locals.jian_jobs = jobs;
        return next();
      }
    });
  };

}).call(this);
