// Generated by CoffeeScript 1.9.3
(function() {
  var func_job;

  func_job = __F('job/job');

  module.exports = function(req, res, next) {
    return func_job.getZans(req.params.id, function(error, zans) {
      res.locals.zan_logs = zans;
      return next();
    });
  };

}).call(this);
