// Generated by CoffeeScript 1.9.3
(function() {
  var func_topic, func_topic_tag;

  func_topic_tag = __F('topic/tag');

  func_topic = __F('topic');

  module.exports = function(req, res, next) {
    return func_topic_tag.getAll(1, 100, null, "sort,id", function(error, tags) {
      var count;
      if (error) {
        return next(error);
      } else {
        res.locals.tags = tags;
        count = tags.length;
        return tags.forEach(function(tag) {
          tag.topics = [];
          return func_topic.getAll(1, 6, {
            tag_id: tag.id
          }, "id desc", function(error, topics) {
            if (topics) {
              tag.topics = topics;
            }
            if ((--count) === 0) {
              return next();
            }
          });
        });
      }
    });
  };

}).call(this);
