// Generated by CoffeeScript 1.9.3
(function() {
  var func_topic_comment;

  func_topic_comment = __F('topic_comment');

  module.exports = function(req, res, next) {
    return func_topic_comment.getAll(1, 10, null, "id desc", function(error, replys) {
      res.locals.recent_replys = replys;
      return next();
    });
  };

}).call(this);
