// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    return (__F('topic')).getAll(1, 10, {
      tag_id: res.locals.topic.tag_id
    }, "sort desc,last_comment_time desc", function(error, topics) {
      res.locals.sametag_topics = topics;
      return next();
    });
  };

}).call(this);
