// Generated by CoffeeScript 1.9.3
(function() {
  var Channel, Users, func_channel;

  Channel = new __BaseModel('qa/channels');

  Users = new __BaseModel('users');

  Channel.sync();

  func_channel = new __BaseFunction(Channel);

  func_channel.getAll = function(page, count, condition, order, include, callback) {
    var query;
    if (arguments.length === 4) {
      callback = order;
      order = null;
      include = null;
    } else if (arguments.length === 5) {
      callback = include;
      include = null;
    }
    query = {
      offset: (page - 1) * count,
      limit: count,
      order: order || "id desc"
    };
    if (condition) {
      query.where = condition;
    }
    if (include) {
      query.include = include;
    }
    return Channel.findAll(query).success(function(ms) {
      return callback(null, ms);
    }).error(function(e) {
      return callback(e);
    });
  };

  module.exports = func_channel;

}).call(this);
