// Generated by CoffeeScript 1.9.3
(function() {
  var func_card, func_user;

  func_card = __F('card');

  func_user = __F('user');

  module.exports = function(req, res, next) {
    return func_user.getById(res.locals.article.user_id, function(error, user) {
      res.locals.writer = user;
      return next();
    });
  };

}).call(this);
