// Generated by CoffeeScript 1.9.3
(function() {
  var func_tag;

  func_tag = __F('tag');

  module.exports = function(req, res, next) {
    if (res.locals.article.tags) {
      return func_tag.getTagsByIds(res.locals.article.tags.split(","), function(error, tags) {
        res.locals.full_tags = tags;
        return next();
      });
    } else {
      return next();
    }
  };

}).call(this);
