// Generated by CoffeeScript 1.9.3
(function() {
  var func_article, func_fav;

  func_fav = __F('user/fav');

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    if (res.locals.article && res.locals.user) {
      return func_fav.getByUUIDAndUserId(res.locals.article.uuid, res.locals.user.id, function(error, fav) {
        if (fav) {
          res.locals.has_fav = true;
        }
        return func_article.getZanByArticleIdAndUserId(res.locals.article.id, res.locals.user.id, function(error, log) {
          if (log) {
            res.locals.has_zan = true;
          }
          return next();
        });
      });
    } else {
      return next();
    }
  };

}).call(this);
