// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    if (res.locals.user) {
      return func_article.checkCanRead(res.locals.user.id, res.locals.article.id, function(error) {
        if (!error) {
          res.locals.can_read = 1;
        }
        return next();
      });
    } else {
      return next();
    }
  };

}).call(this);
