// Generated by CoffeeScript 1.9.3
(function() {
  var func_column;

  func_column = __F('column');

  module.exports = function(req, res, next) {
    return func_column.getRsses(req.params.id, function(error, rsses) {
      res.locals.rsses = rsses;
      return next();
    });
  };

}).call(this);
