// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    console.log('article');
    if (/^[0-9]*$/.test(req.params.id)) {
      return func_article.getById(req.params.id, function(error, article) {
        if (error) {
          return next(error);
        } else if (!article) {
          return next(new Error('不存在的文章'));
        } else {
          res.locals.article = article;
          return next();
        }
      });
    } else {
      return func_article.getByPinyin(req.params.id, function(error, article) {
        if (error) {
          return next(error);
        } else if (!article) {
          return next(new Error('不存在的文章'));
        } else {
          req.params.id = article.id;
          res.locals.article = article;
          return next();
        }
      });
    }
  };

}).call(this);
