// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    return (__F('column')).getById(req.params.id, function(error, column) {
      res.locals.column = column;
      return next();
    });
  };

}).call(this);
