// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    if (res.locals.article.is_buy) {
      return func_article.canReaders(res.locals.article.id, function(error, payers) {
        if (payers) {
          res.locals.payers = payers;
        }
        return next();
      });
    } else {
      return next();
    }
  };

}).call(this);
