// Generated by CoffeeScript 1.9.3
(function() {
  var func_column;

  func_column = __F('column');

  module.exports = function(req, res, next) {
    return func_column.getAll(1, 5, {
      is_jian: 1
    }, "id desc", function(error, columns) {
      res.locals.jian_columns = columns;
      return next();
    });
  };

}).call(this);
