// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    return func_article.getAll(1, 5, ['publish_time>?', (new Date()).getTime() / 1000 - 60 * 60 * 24 * 20], "visit_count desc", function(error, articles) {
      res.locals.jian_hots = articles;
      return next();
    });
  };

}).call(this);
