// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    if (res.locals.user) {
      return (__F('column')).getAll(1, 100, {
        is_public: 1
      }, "last_article_time desc,visit_count desc", function(error, columns) {
        res.locals.public_columns = columns;
        return next();
      });
    } else {
      res.locals.public_columns = [];
      return next();
    }
  };

}).call(this);
