// Generated by CoffeeScript 1.9.3
(function() {
  var func_column;

  func_column = __F('column');

  module.exports = function(req, res, next) {
    return func_column.getAll(res.locals.page, 15, {
      is_publish: 1
    }, "last_article_time desc,visit_count desc", function(error, columns) {
      if (error) {
        return next(error);
      } else {
        res.locals.recent_columns = columns;
        return next();
      }
    });
  };

}).call(this);
