// Generated by CoffeeScript 1.9.3
(function() {
  var func_user;

  func_user = __F('user');

  module.exports = function(req, res, next) {
    return func_user.getById(req.params.id, function(error, user) {
      if (error) {
        return next(new Error('不存在的用户'));
      } else {
        res.locals.who = user;
        return next();
      }
    });
  };

}).call(this);
