// Generated by CoffeeScript 1.9.3
(function() {
  var Talk, func_talk;

  Talk = new __BaseModel('talk/talk');

  Talk.sync();

  func_talk = new __BaseFunction(Talk);

  module.exports = func_talk;

}).call(this);
