// Generated by CoffeeScript 1.9.3
(function() {
  var Blog, User, func_blog;

  Blog = __M('blog/blogs');

  Blog.sync();

  User = __M('users');

  User.hasOne(Blog, {
    foreignKey: "user_id"
  });

  Blog.belongsTo(User, {
    foreignKey: "user_id"
  });

  func_blog = {
    getAll: function(page, count, condition, order, include, callback) {
      var query;
      if (arguments.length === 4) {
        callback = order;
        order = null;
        include = null;
      } else if (arguments.length === 5) {
        callback = include;
        include = null;
      }
      query = {
        offset: (page - 1) * count,
        limit: count,
        order: order || "id desc",
        raw: true,
        include: [User]
      };
      if (condition) {
        query.where = condition;
      }
      if (include) {
        query.include = include;
      }
      return Blog.findAll(query).success(function(ms) {
        return callback(null, ms);
      }).error(function(e) {
        return callback(e);
      });
    },
    getByName: function(name, callback) {
      return Blog.find({
        where: {
          name: name
        }
      }).success(function(b) {
        if (b) {
          return callback(null, b);
        } else {
          return callback(new Error('不存在'));
        }
      }).error(function(e) {
        return callback(e);
      });
    }
  };

  __FC(func_blog, Blog, ['add', 'getById', 'update', 'count', 'addCount', 'delete']);

  module.exports = func_blog;

}).call(this);
