// Generated by CoffeeScript 1.9.3
(function() {
  var Comment, func_comment;

  Comment = __M('job/comments');

  Comment.sync();

  func_comment = {};

  __FC(func_comment, Comment, ['getAll', 'getByField', 'getById', 'delete', 'update', 'count', 'add']);

  module.exports = func_comment;

}).call(this);
