// Generated by CoffeeScript 1.9.3
(function() {
  var Resume, func_resume;

  Resume = __M('job/resumes');

  Resume.sync();

  func_resume = {};

  __FC(func_resume, Resume, ['getByField', 'getById', 'delete', 'update', 'count', 'add']);

  module.exports = func_resume;

}).call(this);
