// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: 'int',
    uuid: "varchar(40)",
    name: "varchar(40)",
    desc: "text",
    important: {
      type: "int",
      defaultValue: 0
    },
    topic_count: {
      type: "int",
      defaultValue: 0
    },
    visit_count: {
      type: "int",
      defaultValue: 0
    },
    sort: {
      type: 'int'
    }
  };

}).call(this);
