// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    md: "text",
    html: {
      type: "text",
      set: function(v) {
        return this.setDataValue('html', xss(v));
      }
    },
    parent_id: "int",
    uuid: "varchar(40)",
    user_id: "int",
    user_nick: "varchar(40)",
    user_headpic: "varchar(255)",
    job_id: "int",
    zan_count: {
      type: "int",
      defaultValue: 0
    }
  };

}).call(this);
