// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    job_id: "int",
    user_id: "int",
    uuid: "varchar(40)"
  };

}).call(this);
