// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    title: "varchar(300)",
    visit_count: {
      type: "int",
      defaultValue: 0
    },
    user_id: "int",
    user_nick: "varchar(100)",
    user_headpic: "varchar(255)",
    tou_count: {
      type: "int",
      defaultValue: 0
    },
    zan_count: {
      type: "int",
      defaultValue: 0
    },
    company_name: "varchar(100)",
    company_personcount: "varchar(100)",
    company_country: "varchar(20)",
    company_city: "varchar(20)",
    company_desc: "text",
    email: "varchar(100)",
    zhiwei: "varchar(100)",
    zhaopin_personcount: "int",
    zhaopin_jingyan: "varchar(20)",
    min_price: "int",
    max_price: "int",
    zhaopin_desc: "text",
    sort: "int",
    is_publish: {
      type: "tinyint",
      defaultValue: 0
    },
    is_jian: {
      defaultValue: 0,
      type: "tinyint"
    }
  };

}).call(this);
