// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "int",
    privince: "varchar(50)",
    city: "varchar(50)",
    zhiwei: "varchar(50)",
    min_price: "int",
    max_price: "int",
    jianli: "varchar(1000)",
    desc: "text"
  };

}).call(this);
