// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    var condition, count, page;
    if (res.locals.user) {
      condition = {
        is_yuanchuang: 0,
        user_id: res.locals.user.id
      };
      page = req.query.page || 1;
      count = req.query.count || 30;
      return (__F('read')).count(condition, function(error, _count) {
        if (error) {
          return next(error);
        } else {
          res.locals.total = _count;
          res.locals.totalPage = Math.ceil(_count / count);
          res.locals.page = req.query.page || 1;
          return (__F('read')).getAll(page, count, condition, function(error, articles) {
            if (error) {
              return next(error);
            } else {
              res.locals.my_reads = articles;
              return next();
            }
          });
        }
      });
    } else {
      return next();
    }
  };

}).call(this);
