// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    return (__F('comment')).getAllByTargetId("card_" + req.params.id, 1, 10, null, function(error, comments) {
      res.locals.comments = comments;
      return next();
    });
  };

}).call(this);
