// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    return (__F('card')).getById(req.params.id, function(error, card) {
      if (error) {
        return next(error);
      } else if (!card) {
        return next(new Error('不存在的名片'));
      } else {
        res.locals.card = card;
        return (__F('user')).getById(card.user_id, function(error, user) {
          res.locals.card_user = user;
          return next();
        });
      }
    });
  };

}).call(this);
