// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    var user_id;
    if (!res.locals.card) {
      return next();
    } else {
      user_id = res.locals.card.user_id;
      return (__F('topic')).count({
        user_id: user_id
      }, function(error, count) {
        res.locals.his_topics_count = count;
        return (__F('topic')).getAll(1, 10, {
          user_id: user_id
        }, function(error, topics) {
          res.locals.his_topics = topics;
          return next();
        });
      });
    }
  };

}).call(this);
