// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    var user_id;
    if (!res.locals.card) {
      return next();
    } else {
      user_id = res.locals.card.user_id;
      return (__F('answer')).count({
        user_id: user_id
      }, function(error, count) {
        res.locals.his_answers_count = count;
        return (__F('answer')).getAllWithQuestion(1, 10, {
          user_id: user_id
        }, null, function(error, answers) {
          res.locals.his_answers = answers;
          return next();
        });
      });
    }
  };

}).call(this);
