// Generated by CoffeeScript 1.9.3
(function() {
  var func_talk;

  func_talk = __F('talk/talk');

  module.exports = function(req, res, next) {
    var count, page;
    page = req.query.page;
    count = req.query.count || 20;
    return func_talk.count(null, function(error, _count) {
      if (error) {
        return next(error);
      } else {
        res.locals.total = _count;
        res.locals.totalPage = Math.ceil(_count / count);
        page = page || res.locals.totalPage;
        res.locals.page = page || 1;
        return func_talk.getAll(res.locals.totalPage - page + 1, count, null, "id desc", function(error, talks) {
          if (error) {
            return next(error);
          } else {
            res.locals.talks = talks;
            return next();
          }
        });
      }
    });
  };

}).call(this);
