// Generated by CoffeeScript 1.9.3
(function() {
  var all_count;

  all_count = __F('all_count');

  module.exports = function(req, res, next) {
    console.log(all_count.data);
    res.locals.all_count = all_count.getData();
    return next();
  };

}).call(this);
