// Generated by CoffeeScript 1.9.3
(function() {
  var func_card;

  func_card = require('./../functions/card');

  module.exports = function(req, res, next) {
    return func_card.getRecents(function(error, recents) {
      res.locals.recents = recents;
      return next();
    });
  };

}).call(this);
