// Generated by CoffeeScript 1.9.3
(function() {
  var func_card;

  func_card = require('./../functions/card');

  module.exports = function(req, res, next) {
    if (res.locals.user && res.locals.user.card_id) {
      return func_card.getById(res.locals.user.card_id, function(error, card) {
        if (card) {
          res.locals.card = card;
        }
        return next();
      });
    } else {
      return next();
    }
  };

}).call(this);
