// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(req, res, next) {
    if (res.locals.user.is_admin) {
      return next();
    } else {
      return res.render('no-permission.jade');
    }
  };

}).call(this);
