// Generated by CoffeeScript 1.9.3
(function() {
  var func_info, func_user, md5;

  func_user = __F('user');

  func_info = __F('info');

  md5 = require('MD5');

  module.exports = function(req, res, next) {
    var p, token, uid;
    if (req.cookies._p) {
      p = req.cookies._p.split(':');
      if (p.length === 2) {
        uid = p[0];
        token = p[1];
        return func_user.getById(uid, function(error, user) {
          if (user) {
            if (md5(user.weibo_token) === token) {
              res.locals.user = user;
              return func_info.count({
                target_user_id: user.id,
                is_read: 0
              }, function(error, count) {
                console.log(count);
                res.locals.unread_count = count;
                return next();
              });
            } else {
              return next();
            }
          } else {
            return next();
          }
        });
      } else {
        return next();
      }
    } else {
      return next();
    }
  };

}).call(this);
