// Generated by CoffeeScript 1.9.3
(function() {
  var func_article;

  func_article = __F('article/article');

  module.exports = function(req, res, next) {
    return func_article.getRecent(function(error, recents) {
      if (recents) {
        recents = recents.splice(0, 10);
      }
      res.locals.recents = recents;
      return next();
    });
  };

}).call(this);
