// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    act_id: {
      type: "int"
    },
    type: "int",
    user_nick: "varchar(100)",
    user_name: "varchar(100)",
    user_headpic: "varchar(255)",
    user_id: {
      type: "int"
    },
    title: "varchar(200)",
    desc: "text"
  };

}).call(this);
