// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: {
      type: "int"
    },
    answer_id: {
      type: "int"
    },
    content: "text",
    user_nick: "varchar(50)"
  };

}).call(this);
