// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    articleid: {
      type: "int"
    },
    tagid: {
      type: "int"
    },
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    }
  };

}).call(this);
