// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    article_id: "int",
    user_id: "int",
    user_nick: "varchar(100)",
    user_headpic: "varchar(255)"
  };

}).call(this);
