// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    from: "varchar(100)",
    fromname: "varchar(100)",
    to: "varchar(100)",
    toname: "varchar(100)",
    text: "text",
    html: "text",
    filepath: "varchar(1000)",
    timestamp: "int"
  };

}).call(this);
