// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    step: "int",
    user_id: "int",
    day: "bigint",
    reason: "varchar(300)"
  };

}).call(this);
