// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    uuid: "varchar(40)",
    user_id: "int",
    column_id: "int"
  };

}).call(this);
