// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    type: "int",
    source_user_id: "int",
    source_user_nick: "varchar(100)",
    target_user_id: "int",
    target_path: "varchar(100)",
    target_path_name: "varchar(100)",
    time: "datetime",
    action_name: "varchar(20)",
    content: "text",
    is_read: {
      defaultValue: 0,
      type: "tinyint"
    }
  };

}).call(this);
