// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    source_mail: "varchar(100)",
    target_mail: "varchar(100)",
    user_id: "int"
  };

}).call(this);
