// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    uuid: "varchar(40)",
    desc: "text",
    audio: "varchar(500)",
    cover: "varchar(500)",
    title: "varchar(200)",
    index: "int",
    visit_count: {
      type: "int",
      defaultValue: 1
    },
    fav_count: {
      type: "int",
      defaultValue: 1
    },
    play_count: {
      type: "int",
      defaultValue: 1
    },
    zip: "varchar(500)"
  };

}).call(this);
