// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    user_id: "varchar(40)",
    push_id: "text",
    music_id: "varchar(500)"
  };

}).call(this);
