// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    uuid: "varchar(40)",
    trade_num: "varchar(100)",
    trade_title: "varchar(200)",
    target_uuid: "varchar(40)",
    trade_price: "double",
    target_type: "int",
    target_user_id: "int",
    alipay_tradenum: "varchar(100)",
    status: {
      defaultValue: 1,
      type: "int"
    },
    buyer_email: "varchar(100)",
    pay_time: "datetime",
    buyer_id: "varchar(40)",
    trade_no: "varchar(40)",
    need_address: {
      type: "tinyint",
      defaultValue: 0
    }
  };

}).call(this);
