// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    question_id: "int",
    user_id: "int",
    reason: "varchar(100)"
  };

}).call(this);
