// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    questionId: "int",
    tagId: "int",
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    }
  };

}).call(this);
