// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    weibo_id: "bigint",
    user_weibo_id: "bigint"
  };

}).call(this);
