// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: 'int',
    name: "varchar(100)",
    desc: "varchar(200)",
    visit_count: {
      type: "int",
      defaultValue: 0
    },
    title: "varchar(100)",
    link: "varchar(1000)"
  };

}).call(this);
