// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    key: "varchar(10)",
    path: "varchar(255)",
    visit_count: {
      type: "int",
      defaultValue: 0
    }
  };

}).call(this);
