// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    uuid: "varchar(40)",
    user_id: "int",
    user_nick: "varchar(100)",
    user_headpic: "varchar(255)",
    answer_count: {
      type: "int",
      defaultValue: 0
    },
    b_zan_count: {
      type: "int",
      defaultValue: 0
    },
    question_count: {
      type: "int",
      defaultValue: 0
    },
    article_count: {
      type: "int",
      defaultValue: 0
    },
    topic_comment_count: {
      type: "int",
      defaultValue: 0
    },
    b_comment_count: {
      type: "int",
      defaultValue: 0
    },
    b_score_count: {
      type: "int",
      defaultValue: 0
    },
    score_count: {
      type: "int",
      defaultValue: 0
    },
    b_invite_count: {
      type: "int",
      defaultValue: 0
    },
    column_count: {
      type: "int",
      defaultValue: 0
    },
    b_visit_count: {
      type: "int",
      defaultValue: 0
    }
  };

}).call(this);
