// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: 'int',
    target_uuid: "varchar(40)",
    target_path: "varchar(100)",
    target_pageId: "int",
    user_id: "int",
    user_nick: "varchar(100)",
    user_headpic: "varchar(255)"
  };

}).call(this);
