// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    blog_id: "int",
    uuid: "varchar(40)",
    url: "varchar(1000)",
    title: "varchar(200)",
    content: "text",
    desc: "text",
    visit_count: {
      type: "int",
      defaultValue: 0
    },
    comment_count: {
      type: "int",
      defaultValue: 0
    },
    user_id: "int",
    time: "varchar(40)",
    tag_id: "int",
    tag_name: "varchar(30)"
  };

}).call(this);
