// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    id: 'int',
    url: "varchar(300)",
    logo: "varchar(500)",
    name: "varchar(100)",
    desc: "text",
    user_id: "int",
    visit_count: {
      type: "int",
      defaultValue: 0
    },
    article_count: {
      type: "int",
      defaultValue: 0
    },
    uuid: "varchar(40)"
  };

}).call(this);
